name: Build Android APK

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout codice
        uses: actions/checkout@v3

      - name: Configura Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Installa dipendenze
        run: |
          npm install
          cd android
          chmod +x gradlew

      - name: Configura Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compila APK in modalità release
        run: |
          cd android
          ./gradlew assembleRelease

      - name: Carica APK come artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-release.apk
          path: android/app/build/outputs/apk/release/app-release.apk
